### ISSUE TITLE
Publish npm to GitHub Packages

### ISSUE THREAD

**Issue by marcjulian** [notiz-dev/design#2]
Should we publish the npm lib to GitHub Packages? Then it is available direct from the repo https://github.com/notiz-dev/design/packages

@garygrossgarten what do you think?

**Comment by marcjulian** [comment]
We can also deploy automatically to npm or GitHub Packages when we create a release

**Comment by garygrossgarten** [comment]
Sure, sounds good

**Comment by marcjulian** [comment]
I added a workflow to publish to NPM when we create a new release. At the moment the release uses `publish:ngx-design` which marks the releases as alpha.

**Comment by marcjulian** [comment]
Installing npm packages from GitHub registry requires an additional configuration step see https://help.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-npm-for-use-with-github-packages#installing-a-package
