### ISSUE TITLE
Tabs layout

### ISSUE THREAD

**Issue by marcjulian** [notiz-dev/design#5]
@garygrossgarten do you want to use the tabs layout for notiz.dev?
If so should we think about the actions in the tabs layout

* search
* all posts
* all tags
* user profile (when we have user login)

**Comment by garygrossgarten** [comment]
Nothing planned. Just to provide a component example with tailwind

**Comment by garygrossgarten** [comment]
we can think about it though

**Comment by marcjulian** [comment]
Tabs could look like this

<img width="1792" alt="Screenshot 2020-04-14 at 22 44 48" src="https://user-images.githubusercontent.com/8985933/79272332-956cee80-7ea1-11ea-9b1b-664bca3850b0.png">

<img width="1792" alt="Screenshot 2020-04-14 at 22 45 34" src="https://user-images.githubusercontent.com/8985933/79272394-aae21880-7ea1-11ea-973d-0acf7b99b11a.png">

**Comment by marcjulian** [comment]
[hashtag](https://fontawesome.com/icons/hashtag) for tags
